hash-format = "sha256"

[[files]]
file = "mods/appleskin.pw.toml"
hash = "8d0321177fed4a0b48554c40158b43db62f6cdaa768f584ef6a11575dfaa6223"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "d02b891b8549c4bacda20466c941001255efd7f184f5ff6bd662ef90c9f6de95"
metafile = true

[[files]]
file = "mods/bellsandwhistles.pw.toml"
hash = "48ddfc4225936a611f738b22b22b48cdc5977715ab75c21ffaa4d36d536e1147"
metafile = true

[[files]]
file = "mods/biomes-o-plenty.pw.toml"
hash = "b0119b17c7c9a075780d55dc87749942a835365db5578102d6250db8875e8267"
metafile = true

[[files]]
file = "mods/bookshelf.pw.toml"
hash = "475a3bafbd5a7b6e8a7f8008f9a137e25a7c0d3474cca99eaa8bfa313899b408"
metafile = true

[[files]]
file = "mods/botania.pw.toml"
hash = "939e093a5dcac4f5437fc267f8ce2c82ddffa13e0912298d4d3b7917a13d1dc6"
metafile = true

[[files]]
file = "mods/botarium.pw.toml"
hash = "098dce9973ba88740458098f574f77cd8611b8aa9584916746ca135ef533309a"
metafile = true

[[files]]
file = "mods/building-gadgets.pw.toml"
hash = "8461b7344559646b5051a6d812e2cd4d43e62c8c817d17f0b2552f65306f43d4"
metafile = true

[[files]]
file = "mods/cb-multipart.pw.toml"
hash = "6f9ada4ae8dfcf29a7071e0eec596d8408e6e9091385db8fd1cddd0c2d89217a"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "e3173aaa4e9078ad7ace2b9ef43ce15ce9919c0b566d8830cea87264f92b3a6a"
metafile = true

[[files]]
file = "mods/codechicken-lib-1-8.pw.toml"
hash = "e4a4617539a9b86d1c55832eeff9116386655525cb4d5fa01034a5c5c16037a6"
metafile = true

[[files]]
file = "mods/comforts.pw.toml"
hash = "6bdf5c00414be2b3bb20d040afe2e90550a300755414aaff01577eed6eaf491f"
metafile = true

[[files]]
file = "mods/connected-glass.pw.toml"
hash = "d5ed5aff0921d0e95d0d470b31fb7ad2d132de4a23adb3096b4c8d1a2020ff79"
metafile = true

[[files]]
file = "mods/cosmetic-armor-reworked.pw.toml"
hash = "cfa8aa9c0437721dab2057c932c9cf8ec3d3a11f672040601305238d13df85e8"
metafile = true

[[files]]
file = "mods/create-big-cannons.pw.toml"
hash = "5ff68b415d1d9bed64dee45a3ea93471627694fa458e1a9e6b5edf22e40d9529"
metafile = true

[[files]]
file = "mods/create-confectionery.pw.toml"
hash = "7f98e3461e1319ef01a91a8258aa2d932179d0406280d980b356ddbfbef52213"
metafile = true

[[files]]
file = "mods/create-misc-and-things.pw.toml"
hash = "67ac69249248ff9b8fe176111a55b71a95dbadd718bb005fa91f9ef6c7b04f36"
metafile = true

[[files]]
file = "mods/create-new-age.pw.toml"
hash = "011d35087c3d81b17000ba7604a73fef600a868021eed8c14df2dc2b77ca7ddc"
metafile = true

[[files]]
file = "mods/create-stuff-additions.pw.toml"
hash = "e357fc625123177d04155eb3edf66a42cc8524aa86410dbb09e857ce036a074b"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "6ecc31d75d379730df8fe950438b4ca26ed1daa8612406374552665f9222f9ea"
metafile = true

[[files]]
file = "mods/createaddition.pw.toml"
hash = "e3675974e82fcae3aa0c612c5a7709739e6c83710ee4d0ccef890afcecc40c87"
metafile = true

[[files]]
file = "mods/cristel-lib.pw.toml"
hash = "4ae2c1b627cfede58a8add7fde29c6d889426aa72ea09a852a402a861aa95166"
metafile = true

[[files]]
file = "mods/cucumber.pw.toml"
hash = "c6c126decfaa56a0fe9f867259a3ea6a71a0da3e19df33b05e0d6592af3a1c74"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "f4d41750be3841d73640ba8f4da3ec8e2e8baef4afef7ecb55dd4afd10588d34"
metafile = true

[[files]]
file = "mods/dank-storage.pw.toml"
hash = "fcb9d8b18068ecdb0c0fa5ca217007f9ae5da735843ce5db80fbf3528d7cc964"
metafile = true

[[files]]
file = "mods/dark-utilities.pw.toml"
hash = "73d04361ac8c44b7128d1acf9bf4384f8e573ff3308065047f8675112540c9c9"
metafile = true

[[files]]
file = "mods/durability-tooltip.pw.toml"
hash = "4a66eb10fbfd1a9cc225eb6c4eadfc03a7938e0427641d25802b7d32748f7a11"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "5b5868d9da5c3d76ea1edf2fd19e7b1612e599a625f8e6ef6bf56859df0783b3"
metafile = true

[[files]]
file = "mods/explorify.pw.toml"
hash = "c8413d40d9e9d2897a45a19dca87c181a46c32a88b7dd5b05f898a0a92b15e36"
metafile = true

[[files]]
file = "mods/extreme-reactors.pw.toml"
hash = "ae35b0e7ec607be388591b121a99cda159344173570512a9a392aaec6a8e40bd"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "dec4a848fbbd45662a533444aa0749c230deb718b5117ceb279963e91ac78f85"
metafile = true

[[files]]
file = "mods/flib.pw.toml"
hash = "aaaae1c159be64f990d869e13bc75bc237d3850d2f3c42472b3b842670651697"
metafile = true

[[files]]
file = "mods/flux-networks.pw.toml"
hash = "de63df967225278681e18afe0e323110322ec02006746980fbe77dbd974b20b3"
metafile = true

[[files]]
file = "mods/fusion-connected-textures.pw.toml"
hash = "59d22263e36313c43ad7c5e4179cb3554d414f701442b0784d94c0ba2384edfd"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "021bf9542f93777cabd29383ea215d521c93ccaef1a57e93825690e314699a93"
metafile = true

[[files]]
file = "mods/immersive-aircraft.pw.toml"
hash = "e50f67e37775aca9ee5c5a1c91bd8e10846f8077e20ace467e4acb7892e1aca0"
metafile = true

[[files]]
file = "mods/industrial-foregoing.pw.toml"
hash = "061ac4235ce0f5b80e35acaebf4b089dd092b7a7e50131ade7b2e2119190325c"
metafile = true

[[files]]
file = "mods/iron-jetpacks.pw.toml"
hash = "b91ac19fe7d6e49db1cbcd01e5f541e124251899f0201b26087e65887cdb300a"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "b9e82527f9d5d2152c4e095c00a3d0a30a29825479fd73e7e24a2634bde112be"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "826c59a1e607641acb85f1e23a2bb7183a2f0a9ccd19ea4f01bbc9d94d480acf"
metafile = true

[[files]]
file = "mods/luggage.pw.toml"
hash = "1b44cbb394ebb487a960c778048da90b020042fd7958e410cf25312e322eb799"
metafile = true

[[files]]
file = "mods/macaws-bridges.pw.toml"
hash = "a4ff567d52fe55984cc0cb93430a4c8f01dc00b14fbd6e25a077dbd179f534fb"
metafile = true

[[files]]
file = "mods/macaws-doors.pw.toml"
hash = "2f496bb621dfb96749e2871ebc28edce95d96d7446775d4acba8fa46e2b353e2"
metafile = true

[[files]]
file = "mods/macaws-furniture.pw.toml"
hash = "593c82516290584155ff30c818f57ba45f28da354206d81b76806f395d883054"
metafile = true

[[files]]
file = "mods/macaws-lights-and-lamps.pw.toml"
hash = "7dda945755d1af637c66ec5da4100f34441cd7da8529bc6c10a57d8d59a84175"
metafile = true

[[files]]
file = "mods/macaws-roofs.pw.toml"
hash = "814eb30339dae8d7aaf2e6d7f12a37300747c3142e6d4bb8dc2ce5ece43960b3"
metafile = true

[[files]]
file = "mods/macaws-trapdoors.pw.toml"
hash = "d05fa9b51d6f853ab901d6c091b089a4b0f4e6d46a0a71d2cf63307568d02004"
metafile = true

[[files]]
file = "mods/magnum-torch-forge.pw.toml"
hash = "5f6768157929bccb85b4b561fb4e16c99018ad93ce3f53b945ab9b37307c3665"
metafile = true

[[files]]
file = "mods/mcjtylib.pw.toml"
hash = "c7912aabbb629d0fb2d1c0cecf0923a1742feae7056dd1b9feb2c81b2c9aef73"
metafile = true

[[files]]
file = "mods/mekanism-explosives.pw.toml"
hash = "d1995ea481f7cdf437fd871e2f37a8d2d09932b15fb9a3096855a387679cbd93"
metafile = true

[[files]]
file = "mods/mekanism-tools.pw.toml"
hash = "733a43ca882f4f38b497bd48cf34106079ccc600a1f1d57867d3f93e68d234a2"
metafile = true

[[files]]
file = "mods/mekanism-weapons.pw.toml"
hash = "8b476758d02df45e5456ca3364d8d8994341bd6c646d43f00f2106f6565f8035"
metafile = true

[[files]]
file = "mods/mekanism.pw.toml"
hash = "e7695cb9ca190c1da74abbc43643d63f94cf517163756c4615c84d83fa72240b"
metafile = true

[[files]]
file = "mods/mining-gadgets.pw.toml"
hash = "d4a42351be29d476b540e810a2339b05f2f0cf789d62404da7c708b685c9ecda"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "9c29166ac593cc02740a23ead3862f61a78d733e3c72567413ed6ef19f85e182"
metafile = true

[[files]]
file = "mods/modular-powersuits.pw.toml"
hash = "5213246e204c8305badeb3a186bae869bce3adc783dc1d0ec19b6b8875b3d04a"
metafile = true

[[files]]
file = "mods/netherportalfix.pw.toml"
hash = "820d6b97344411476b96ae2bc8a3e4b9e30e15dfd15d8d0c945726b0011928d4"
metafile = true

[[files]]
file = "mods/numina.pw.toml"
hash = "871cb13d35c5fbdd5d358953f4fdcac35cf0b3880bad1ad6368f8509861d5eca"
metafile = true

[[files]]
file = "mods/openblocks-elevator.pw.toml"
hash = "9d66478fde6c978312f93734d481bcb9ae9c49b74cb4538fce58c65ef15d593c"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
hash = "3a7eaa64434e7449e5fe6bd089bc784499432dae7d6ca07174b55b10a3b32ec8"
metafile = true

[[files]]
file = "mods/pig-pen-cipher.pw.toml"
hash = "f896fefa7466845181da9db06ba4a89865f54b406ff3b1fb65773c66614b6f1b"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "26bdb83bbbf415d54995cf1c2a32c76901d4c00811704b420cc8de99a919a5ec"
metafile = true

[[files]]
file = "mods/refined-storage-addons.pw.toml"
hash = "70b949dab65474c3687c98063f66282c7a580e0bf82f33615fac247fdc29019b"
metafile = true

[[files]]
file = "mods/refined-storage.pw.toml"
hash = "4f8fa2d8bba834bac3240024294ff9f2881fe20e11d775a93497dec5d25be571"
metafile = true

[[files]]
file = "mods/rftools-base.pw.toml"
hash = "56ceaaa03bebe47af0cab04dba631fd17269a75f079ecf368e1cd90131a67073"
metafile = true

[[files]]
file = "mods/rftools-builder.pw.toml"
hash = "d8e2553b0ec8c23385522171dcfb5460b1d0ec2027119655197366c83ffdb4a3"
metafile = true

[[files]]
file = "mods/rftools-control.pw.toml"
hash = "cc2dcec181cca133808ea514fbd00a236a9ef0b25fb872c43f7af9c89784522d"
metafile = true

[[files]]
file = "mods/rftools-dimensions.pw.toml"
hash = "51ea1e27a8a996271205f144c61ad9ef4c91dbe5d6efb92ec8fdf561ed73344a"
metafile = true

[[files]]
file = "mods/rftools-power.pw.toml"
hash = "d282db574ec0a8c9e6a9d249e8ffca5015c995a21849c7874559f85f72b638df"
metafile = true

[[files]]
file = "mods/runelic.pw.toml"
hash = "53254c5c7af6238845518f9e289b8b91337e88b6dad4566c2e1b223f6901f456"
metafile = true

[[files]]
file = "mods/serene-seasons.pw.toml"
hash = "84ba27cb7bd05174860dba55739d5252f74effd0d77e16383b6c46052fb1774b"
metafile = true

[[files]]
file = "mods/simple-tomb.pw.toml"
hash = "0f6036e1482ea786d4dea4d484d210c8833a9c2d95e8b6b3bb09c9678b51a064"
metafile = true

[[files]]
file = "mods/slice-and-dice.pw.toml"
hash = "5b8044347814e2099c47058c60680376c5acf64f6e87124d1734ae23aeb183fc"
metafile = true

[[files]]
file = "mods/storage-drawers.pw.toml"
hash = "ce92a2870c50085508caf9b680efffdfdd50b54e240e7bf047b6833c66ac139e"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
hash = "3eede8a7ebafb69840153ff51dbc879b0232799e90a834ab6d71274b1316179f"
metafile = true

[[files]]
file = "mods/supermartijn642s-core-lib.pw.toml"
hash = "436e0c633a689379dfb99745344a6ab0c9cc39955f59d6194aad2a6a44202217"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
hash = "4ffe582cac7b3cea7278ba2246d392df7240b45c2cdb74243025c8a4c1650894"
metafile = true

[[files]]
file = "mods/the-twilight-forest.pw.toml"
hash = "160e6c86655e71ce18b4ac3463ba9eccf51e405a6846541536e95371b0063929"
metafile = true

[[files]]
file = "mods/titanium.pw.toml"
hash = "1acbc7abba0a1012489c73c5bfcc692304317cdc03066af009271062d8ee2ec9"
metafile = true

[[files]]
file = "mods/toms-storage.pw.toml"
hash = "f29648fa88935462151aeb43e377f99226130f1181d9dfa53279a1801c9d3cee"
metafile = true

[[files]]
file = "mods/towns-and-towers.pw.toml"
hash = "00a0cba74675174812eea16aca533adfe9bac7b30a81a7e33dd81bd9343b45c4"
metafile = true

[[files]]
file = "mods/translocators-1-8.pw.toml"
hash = "8f212385487bd1419574a097e1311b31bea581904998761727c6c4d82373e716"
metafile = true

[[files]]
file = "mods/trash-cans.pw.toml"
hash = "13af80b2b1274ebea8a8afdd31340b98280ae70ae7a64061162d0b07e75e0929"
metafile = true

[[files]]
file = "mods/travelers-backpack.pw.toml"
hash = "4de745bf044302b2fe9eadfbe9c4bbd2db9c8d8d6e486a8bbffa9858632ef9b6"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
hash = "5f7c7bb29895141d57fdc32823a169e3a851176760f8ceed6c00bc109b4288df"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "0a4855063cd7fe757788aa3bc2ef8cc99d4c7908ddfb642e05838b937878e78b"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "232027893fcd366f56d465821d883830477641b8cef5871add2bdc998ae2503c"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
hash = "0604af4500f5e7ea46e38f7faef3459023c305b3155eacbf406e600073f643d9"
metafile = true

[[files]]
file = "mods/yungs-better-desert-temples.pw.toml"
hash = "88273436c5fc0efecdd61d4615992ae76835b7f88aab2d0f9047b1dc3ec9a5e5"
metafile = true

[[files]]
file = "mods/yungs-better-dungeons.pw.toml"
hash = "8046bfec2206ca605e19cf458ba78d916ce3fafa1ccd9ff07ce0712a45a4063d"
metafile = true

[[files]]
file = "mods/yungs-better-end-island.pw.toml"
hash = "eb89c7d6a1c7eeba70189cf2ad777b4ed5afba7ed2c6a40fb34eb3fad71419c8"
metafile = true

[[files]]
file = "mods/yungs-better-jungle-temples.pw.toml"
hash = "e5d9eba7b883a5bed97e98d97b0291f584d3de1696afe4d00f14585b579b6095"
metafile = true

[[files]]
file = "mods/yungs-better-mineshafts-forge.pw.toml"
hash = "5ded53795031472b64e165faf04adc21d7181854e4d9d2c83fea7b7b12ab3ddf"
metafile = true

[[files]]
file = "mods/yungs-better-nether-fortresses.pw.toml"
hash = "a3adfd6be62c3540b81cb117a71d68d4021ae7d4a85486599eb5028cd8692b7d"
metafile = true

[[files]]
file = "mods/yungs-better-ocean-monuments.pw.toml"
hash = "131843ce0d9cea505760b3903bc4bbe9b39e9f2ec0e155311c0eaa87f7faa428"
metafile = true

[[files]]
file = "mods/yungs-better-strongholds.pw.toml"
hash = "50c709e0297001b0825179335e9f8c81d802740612497e1d231abb19b2fef6bc"
metafile = true

[[files]]
file = "mods/yungs-bridges.pw.toml"
hash = "97a03cf27afe3b50d3b9e97b79fda3e30a6d74e3b3c3fee3db28a4d7b20bc516"
metafile = true

[[files]]
file = "mods/yungs-extras.pw.toml"
hash = "fa202c052bee239aa8c074e13da7c843cda83a2b768769b3d6ae0bc47b11de8e"
metafile = true

[[files]]
file = "mods/zerocore.pw.toml"
hash = "60fd10d77b6b1c06696b082895f75e1de441d9a3b31c5b6289461d0445318a5f"
metafile = true

[[files]]
file = "test.sh"
hash = "db7892756485b6c8f07d7e58a83e72968b8be6e1230a0eec44becb31ab2b41aa"
