name = "eris"
author = "zlataovce"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8d95825a20f2cf45fbc01df66c579cebeb3844e86d2386f19602b59cb88e8433"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"
