hash-format = "sha256"

[[files]]
file = "mods/ad-astra.pw.toml"
hash = "da42d2a6e6e3f7bd10df625ab23d6ba8a50ecb3545c1c3c6bda4f826caa5d51b"
metafile = true

[[files]]
file = "mods/advanced-backups.pw.toml"
hash = "cbc8db716459ff5804441400382314acc303919f6357ec09c708e4cb75efe9cc"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "8d0321177fed4a0b48554c40158b43db62f6cdaa768f584ef6a11575dfaa6223"
metafile = true

[[files]]
file = "mods/aquaculture-delight.pw.toml"
hash = "624514fd57a5bad649068f8f2d6c45d88228249a266bd61b45cb749c42499766"
metafile = true

[[files]]
file = "mods/aquaculture.pw.toml"
hash = "c4ba20c9dc88687865d5c9dd2b6e0043a69055c46b8fd935dd74c43ee56b5428"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "5e9edd1fd2395f14a0c8a4acbdbdd61e1047be1f0033deb3140d2ce0d093e9d8"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "f8b6ef08945410e1341212a2723477487fb66a2c8fd67dd201433658791d298d"
metafile = true

[[files]]
file = "mods/botania.pw.toml"
hash = "8c0f450f657efab9f25ae5bc6dfb6a43aafc0e7e411fea8df2c885593bb67fde"
metafile = true

[[files]]
file = "mods/botarium.pw.toml"
hash = "008c942efc2e2ec221dd1a760b4a50e2f24ede37747731ba794f5e845554adcb"
metafile = true

[[files]]
file = "mods/brewin-and-chewin.pw.toml"
hash = "dc45e2a3431d818f9bb2b7217a62e62ec8f455ca37b9f4f35947d2c442bad42b"
metafile = true

[[files]]
file = "mods/butchery.pw.toml"
hash = "e1ee1f538bf86994b81e95d25801c97712e6877014fe8e4b0db2f280370fd408"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "e3173aaa4e9078ad7ace2b9ef43ce15ce9919c0b566d8830cea87264f92b3a6a"
metafile = true

[[files]]
file = "mods/corgilib.pw.toml"
hash = "28053b4a334c4079b5d4c7ea2d3b8d48f8fa61420498f1bed0ff83cd316bbba0"
metafile = true

[[files]]
file = "mods/create-diesel-generators.pw.toml"
hash = "aea24bc376b53b12d049633a2be9a9911fb6984e189940e804e74bc9fcf921a0"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "9d7971a7af2ff4a96a0e5aede76f9cf8dc978da601e2754f79d6ec8631125bb9"
metafile = true

[[files]]
file = "mods/createaddition.pw.toml"
hash = "8a5f33277995fccd2be6793c4fba1b5d657983be32f0b47e4afab4eac70b8ab8"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "1315cd56b0b4a5b3d53374cebf4f1f3cd0546b05058740847bd226c1d1ccab39"
metafile = true

[[files]]
file = "mods/embeddium.pw.toml"
hash = "a1575677daaaf6ea6dac12e5a10073e34025e5ca2c35b6d36ad4a5a0edbc0e82"
metafile = true

[[files]]
file = "mods/ender-io.pw.toml"
hash = "20408dc8b2d5965858fac965195ba1e7b4b3bf7da1bd9600d335fa1950924884"
metafile = true

[[files]]
file = "mods/eureka-ships.pw.toml"
hash = "c61734cdfd93db9cc1509659e5719d8db79ffafec8eb9832776a0253f6096cdf"
metafile = true

[[files]]
file = "mods/ex-compressum.pw.toml"
hash = "896a1ebc9e52451308ffac3aace6c7d96ef3293322f1af525687ca8049d832e3"
metafile = true

[[files]]
file = "mods/exnihilosequentia.pw.toml"
hash = "300cc3a44986433790c8ff20352743eda4ac8371a2c5e5b0140596564737678b"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "067fc433511066d18b1795b86c9856246a8da7f9a4316afd6b25e5eee181f660"
metafile = true

[[files]]
file = "mods/farmers-respite.pw.toml"
hash = "49431cb48a66b264c2cb7702c7bb80155d1a59a42d384348e30700ce0ebc1e4c"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
hash = "5bd0506bc0be25116b234f2b5af9447f60d82ae1cb6c5be4e12d8841f6c2501c"
metafile = true

[[files]]
file = "mods/ftb-chunks-forge.pw.toml"
hash = "0e753f0aea9277eba730d4a55929f244f9d7c9d15cc5e9bd96b4669e531f6de2"
metafile = true

[[files]]
file = "mods/ftb-library-forge.pw.toml"
hash = "691798dd9acfd386bc9332249cd4c1291c646af4d97999090ec0528d9bb35c88"
metafile = true

[[files]]
file = "mods/ftb-teams-forge.pw.toml"
hash = "450e23b3e692360eee6fd55fc640b391eff8f4e5714ccc69bafb837685ae8e96"
metafile = true

[[files]]
file = "mods/ftb-ultimine-forge.pw.toml"
hash = "1c383e66311b5edd6d7116ae0544108d60450f58e94853126665d75d85561d68"
metafile = true

[[files]]
file = "mods/fusion-connected-textures.pw.toml"
hash = "e17f96677912ca1e42ab05ba1e959226c7b5244f6a24eb573ace63f57e6c222f"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "88f142bda6bfa6aff4f4d4e12b8ba7581aa40e3f163039a533f09dd6d634e093"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "c949e6e0d6a70b8693ef48f8f205cb4fb967cc7c2ecbe029ffe7809e36ad5138"
metafile = true

[[files]]
file = "mods/industrial-foregoing.pw.toml"
hash = "762fded46cec5b2f224483c9fac2248184d8b88144556021be75a7f3c05c2da8"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "d0468c50463003c3be730e99937e3444d617fb174440f71ed5fd5948a5ff969f"
metafile = true

[[files]]
file = "mods/journeymap-integration.pw.toml"
hash = "d439ee315a5f488532f8dd9c6f8055945f13bce067a4622cf547bd35408c3cd6"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "664a573384edf644e9b788c7c29fe32593917ac8283bb794cc46b471a0a6504a"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "40026875ee9b7d25a4ece48faa2b70a338100e87a689d5a8d4ba1ee608b878f6"
metafile = true

[[files]]
file = "mods/lendercataclysm.pw.toml"
hash = "75199fa3b762c5aa781e3cb2aab7779d19128b2a1c5b15798d5e613df8d16573"
metafile = true

[[files]]
file = "mods/lionfish-api.pw.toml"
hash = "60af8798dbf3e300a5af44125595afcd5d1e70072448444156364f222cc03e98"
metafile = true

[[files]]
file = "mods/mantle.pw.toml"
hash = "4f818ebe7421a0ae41154fb479273dab515993b76c194c815d824f98e4f53a5e"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "373b18020e519fa602dc3e5ecc7d9d1523a353ddec85b20fe8dbbad23d4e7db2"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "e72f73611904e14d915418f0e3c6cb483cdc600e211375c2eceb393fec5b80f1"
metafile = true

[[files]]
file = "mods/novacore.pw.toml"
hash = "593899fa3133de24cdd943513530a0612ebf9ac48f0bc9b9da705744a7f4429f"
metafile = true

[[files]]
file = "mods/oculus.pw.toml"
hash = "200f79b635a087841698c85ac7028f0a1fac2cc4ffae1d59ff3f07a94abfe70e"
metafile = true

[[files]]
file = "mods/oh-the-biomes-weve-gone.pw.toml"
hash = "31656203172b1ecf76e38e9d957dba3694a15b7972dd49eea49c7b61c19d70c4"
metafile = true

[[files]]
file = "mods/oh-the-trees-youll-grow.pw.toml"
hash = "060967c337239159637dc07818af3020eb7c323102fe21f4171645c030e3fec7"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
hash = "dec2bc011d4ca1d451aaa3eea477f13366bfb13beba0716018f47d9331a50d8e"
metafile = true

[[files]]
file = "mods/rechiseled-create.pw.toml"
hash = "5bac1063d07c12c591dbcb1d7aea39ee863c73e84951334ebeec2754d22843da"
metafile = true

[[files]]
file = "mods/rechiseled.pw.toml"
hash = "3e8c59c1817babb68d49af1bd816d6d00ffbaa8343968ad324996a0d5deb9c69"
metafile = true

[[files]]
file = "mods/refined-storage-addons.pw.toml"
hash = "70b949dab65474c3687c98063f66282c7a580e0bf82f33615fac247fdc29019b"
metafile = true

[[files]]
file = "mods/refined-storage.pw.toml"
hash = "4f8fa2d8bba834bac3240024294ff9f2881fe20e11d775a93497dec5d25be571"
metafile = true

[[files]]
file = "mods/resourceful-config.pw.toml"
hash = "e242387207a2538b5ccb55697174c65e549e1eb2fef9da37e1ad3734e0372b65"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "ef0264b7d819848f72ab2f34643306187e712965a8246e1f733e1bd39d8fd681"
metafile = true

[[files]]
file = "mods/slice-and-dice.pw.toml"
hash = "9b59e9b08c1281a521777e9924dab6c258e42c5d1c06852b9ebe9304021aec42"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks-create-integration.pw.toml"
hash = "0462f0b658c766e1ccb9974f576090713738606d6513aba89cf8d5ba2b00847b"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks.pw.toml"
hash = "3bb4a9500b84afbceb8d426505a1727888aa53de23f839ce261fe6956491cc83"
metafile = true

[[files]]
file = "mods/sophisticated-core.pw.toml"
hash = "4e0171baa817919422b027a64d97ef8ffc63879c94671b2fc42f191cc6f3900d"
metafile = true

[[files]]
file = "mods/sophisticated-storage-create-integration.pw.toml"
hash = "6a35429fa6de146d4341307a8d3d75aa37e05b1d67b564568bb0d55720deafa2"
metafile = true

[[files]]
file = "mods/sophisticated-storage.pw.toml"
hash = "8d70c2a187f0d9d94d9e70d4ab2c3e2c148e363b3f8859dcbee0e5c96eaf95d0"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
hash = "3eede8a7ebafb69840153ff51dbc879b0232799e90a834ab6d71274b1316179f"
metafile = true

[[files]]
file = "mods/supermartijn642s-core-lib.pw.toml"
hash = "4ddff1daf862f7e481a6c30c4cbb4bb32165f2c73cefc908dbf62b18f0d46a56"
metafile = true

[[files]]
file = "mods/tcintegrations.pw.toml"
hash = "8d93b245da89b2de3dfe3f8ddc2c24184b23060efb4c61e9c30eeecbbb8dd76a"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
hash = "fde3d3b1607636100e382dce1bba80ab4608ebfa1ef888a37b86bc8c7dcbafe5"
metafile = true

[[files]]
file = "mods/tesseract.pw.toml"
hash = "0188496a2cffbd5a1aad3fa0429d646487bd685aa2b109c2c649aff675c91a6c"
metafile = true

[[files]]
file = "mods/the-one-probe.pw.toml"
hash = "97063e6b0b10ed95e42c1d4954ab577f8d6e94a79c0a8a93206b35475dce1460"
metafile = true

[[files]]
file = "mods/the-twilight-forest.pw.toml"
hash = "d1f859de9867b7433305aef1631aa22a436a4c3924474a21c0a22ab5f2093c04"
metafile = true

[[files]]
file = "mods/tinkers-construct.pw.toml"
hash = "da92e9606b616857fd108d05d713d93cd9f6c586ed00ca0b696cc90f19eba6b4"
metafile = true

[[files]]
file = "mods/tinkers-levelling-addon.pw.toml"
hash = "66fd483f4311166307c184c29f3e81f56179ed5ab094328b2c1413e91ba4c68a"
metafile = true

[[files]]
file = "mods/titanium.pw.toml"
hash = "5e41fd8f565e09e83868e4c4776154befd3203b01ed5f09b6f7cd27687ec0041"
metafile = true

[[files]]
file = "mods/valkyrien-skies.pw.toml"
hash = "bf1649e3020c6738600cae50627dd4db8eb63a6b9c200efa89c8589c3ff29505"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
hash = "5dbc1ed70c1dd5c99c93d353b6267c6a4e7af2b342d0ad4ddecf54593e199224"
metafile = true

[[files]]
file = "resourcepacks/fusion-connected-blocks.pw.toml"
hash = "b5395a87ff650ccd9253568779f85deebf8186645219d4c6461f78645f03f0bd"
metafile = true

[[files]]
file = "resourcepacks/fusion-connected-glass.pw.toml"
hash = "9558758e85c4d4e25da6c62d2381e24de2794f1307136ee9b4be98ed32baf6ad"
metafile = true

[[files]]
file = "shaderpacks/complementary-unbound.pw.toml"
hash = "006170836f3180d229a6b95e1b33c060d7afcd0755273669faf78e86f50579ed"
metafile = true
