name = "dark"
author = "zlataovce"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd30da48595543e7293605f513ae575f19a5dc75f1d5517b6a1104fe37cd204f"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
