name = "dark"
author = "zlataovce"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d8a562ae54b747297eb725baf6b9ed4c2e5e1bf13a02420215062078de3f1c3b"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
