name = "dark"
author = "zlataovce"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "31540e39d2d07564a514a1c289fb3c3001b95c00f5775d6c08321909edcab5dd"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
